name: morning
on:
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      USER_ID_2: ${{ secrets.USER_ID_2 }}
      DATE_FROM: ${{ secrets.DATE_FROM }}
      DATE_TO: ${{ secrets.DATE_TO }}
      FRI_SP: ${{ secrets.FRI_SP }}
      HOME_CITY: ${{ secrets.HOME_CITY }}
      IS_SCHOOL: ${{ secrets.IS_SCHOOL }}
      SCHOOL_CITY: ${{ secrets.SCHOOL_CITY }}
      WEEKEND_SP: ${{ secrets.WEEKEND_SP }}
      WEATHER_ID: ${{ secrets.WEATHER_ID }}
